#ifndef AST_CONCRETE_NODES_H
#define AST_CONCRETE_NODES_H

// Below is generated from makeAbstractVisitor.py
//START INCLUSION POINT
#include "action_list.h"
#include "action_stmt.h"
#include "arg.h"
#include "arg_list.h"
#include "assign_stmt.h"
#include "bbcall.h"
#include "bi_var_decl.h"
#include "binary_expr.h"
#include "blackboard_decl.h"
#include "cond.h"
#include "cond_stmt.h"
#include "elif_stmt.h"
#include "else_stmt.h"
#include "empty_action_list.h"
#include "empty_arg_list.h"
#include "empty_para_list.h"
#include "empty_tr_prog_list.h"
#include "exit_stmt.h"
#include "expr_stmt.h"
#include "fcall.h"
#include "func_decl.h"
#include "ident.h"
#include "if_stmt.h"
#include "init_expr.h"
#include "literal_expr.h"
#include "logic_stmt.h"
#include "once_decl.h"
#include "operator.h"
#include "otherwise_stmt.h"
#include "para_decl.h"
#include "para_list.h"
#include "regression_stmt.h"
#include "return_stmt.h"
#include "tr_node.h"
#include "tr_prog_list.h"
#include "tr_program.h"
#include "unary_expr.h"
#include "var_decl.h"
#include "var_expr.h"
//END INCLUSION POINT

#endif
